flaskblog/cursos/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

cursos = Blueprint('cursos', __name__)


@cursos.route("/capacitacao", methods=['GET', 'POST'])
@login_required
def capacit():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('capacit.html', posts=posts)

flaskblog/main/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.models import Post

main = Blueprint('main', __name__)


@main.route("/home")
@login_required
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)



@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route("/produtores")
@login_required
def produtores():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('produtores.html', posts=posts)

flaskblog/noticias/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Noticia 
from flaskblog.noticias.forms import NoticiaForm

noticias = Blueprint('noticias', __name__)


@noticias.route("/noticias", methods=['GET', 'POST'])
@login_required
def news():
    page = request.args.get('page', 1, type=int)
    posts = Noticia.query.order_by(Noticia.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('news.html', post=noticias)

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Sua postagem foi criada!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='Nova Postagem', form=form)


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Sua postagem foi atualizada')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form,  legend='Nova Postagem')

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post ha been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


@users.route("/", methods=['GET', 'POST'])
@users.route("/enter", methods=['GET', 'POST'])
def enter():
    if current_user.is_authenticated:
            return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('enter.html', title='Login', form=form)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
            return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Sua conta foi criada!', 'success')
        return redirect(url_for('main.home'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
            return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file 
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('suas informações foram atualizadas', 'sucesso')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file) 
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)

@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/user/myposts")
def myposts():
    username1 = current_user.username
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username1).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route("/reset_password", methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Um email foi lançado com instruções para resetar a senha.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token()
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Sua senha foi atualizada!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}	
{% block content %}
<div class="card-deck">
<div class="card" style="width: 18rem;"><h1></h1>
  <div class="card-body">
    <h2 class="card-title">Sobre a AGCO²</h2>
    <p class="card-text">Somos uma ONG que busca entrar em contato com cooperativas na região norte do país e oferecer
    o uso da plataforma de rede social da AGCO², um espaço aonde os produtores podem se manter informados, capacitados e conectados
    sobre o plano ABC+, podendo medir seu desempenho nas metas ABC+.</p>
    <a href="https://www.gov.br/agricultura/pt-br/assuntos/sustentabilidade/agricultura-de-baixa-emissao-de-carbono/publicacoes/abc-portugues.pdf" class="btn btn-primary">Saber mais sobre o ABC+</a>
  </div>
</div>

<div class="card" style="width: 18rem;"><h1></h1>
  <div class="card-body">
    <h2 class="card-title">Investimentos</h2>
    <p class="card-text">Se você é uma empresa que deseja
    fazer investimentos neste mercado renovável, entre em
    contato conosco.</p>
    <a href="#" class="btn btn-primary">Investir no AGCO²</a>
  </div>
</div>
</div>
{% endblock content %}

flaskblog/templates/capacit.html
{% extends "layout.html" %}
{% block content %}
<div class="card-deck">
<div class="card" style="width: 18rem;"><h1></h1>
 <img class="card-img-top" src="https://ruralpecuaria.com.br/painel/img/noticias/8689/noticias_1507221889.jpg" alt="Plantio Direto">
  <div class="card-body">
     <h2 class="card-title">Plantio Direto - SDP</h2>
    <p class="card-text">Aprenda sobre os métodos de plantio direto
    e como eles podem reduzir a emissão de CO2eq, gerando sustentabilidade e
    melhores resultados no plantio</p>
    <a href="#" class="btn btn-primary">Inscrever-se</a>
  </div>
</div>
<div class="card" style="width: 18rem;"><h1></h1>
  <div class="card-body">
	  <img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIt7-_W4b6Etj55pHfvVAk07CuTU4n-xJT86rH6q6v-ISVAUnskPR5f_TNEf0BUBQtu08&usqp=CAU">
    <h2 class="card-title">Abordagem Integrada de Paisagem - IAP</h2>
    <p class="card-text">A AIP considera que a gestão do território agropecuário
    deve levar em conta os diversos elementos da paisagem rural, em seus
    diferentes níveis e escalas, refletindo seu aspecto diversificado,
    sistêmico e dinâmico.
    </p>
    <a href="#" class="btn btn-primary">Inscrever-se</a>
  </div>
</div>
</div>
<div class="mt-4 card-deck">
<div class="card" style="width: 18rem;"><h1></h1>
  <div class="card-body">
	  <img class="card-img-top" src="https://www.myfarm.com.br/wp-content/uploads/2021/09/348355.jpg" alt=ILPF>
    <h2 class="card-title">Integração Lavoura Pecuária Floresta -ILPF</h2>
    <p class="card-text">
   A iLPF é uma estratégia que visa a produção sustentável, que integra atividades agrícolas, pecuárias e florestais realizadas na mesma área, em cultivo consorciado, em sucessão ou rotacionado.
    </p>
    <a href="#" class="btn btn-primary">Inscrever-se</a>
  </div>
</div>
<div class="card" style="width: 18rem;"><h1></h1>
  <div class="card-body">
	 <img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLxvb4qJxBbEfd8EtwTCaU00ofycFBbo13mudEgZo3iQ&s" alt="Fixação Biológica">
	  <h2 class="card-title">Fixação Biológica de Nitrogênio - FBN</h2>
    <p class="card-text">
    A Fixação Biológica de Nitrogênio (FBN) é um processo natural que ocorre em associações de plantas com bactérias diazotróficas. Seu principal produto, o nitrogênio, é um nutriente essencial para o crescimento e o desenvolvimento vegetal.
    </p>
    <a href="#" class="btn btn-primary">Inscrever-se</a>
  </div>
</div>
</div>
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">{{ legend }}</legend>

				<div class="form-group">
					{{ form.title.label(class="form-control-label") }}
						{% if form.title.errors %}
							{{ form.title(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.title.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.title(class="form-control form-control-lg") }}
					{% endif %}

				</div>

				<div class="form-group">
					{{ form.content.label(class="form-control-label") }}
						{% if form.content.errors %}
							{{ form.content(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.content.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.content(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info")}}
			</div>
		</form>
	</div>
{% endblock content %}

flaskblog/templates/enter.html
{% extends "layoutun.html" %}
{% block content %}

        <div style="z-index: 1;" class="col-md-7">
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Entrar</legend>

				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
						{% if form.email.errors %}
							{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}

				</div>

				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
						{% if form.password.errors %}
							{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-check">
					{{ form.remember(class="form-check-input" )}}
					{{ form.remember.label(class="form-check-label" )}}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info")}}
			<small class="text-muted ml-2">
				<a href="{{ url_for('users.reset_request') }}">Esqueci a senha!</a>
			</small>
			</div>

		</form>
	</div>
	</div>
	<div>
		<small class="text-muted">
			Precisa de uma conta? <a class="ml-2" href="{{ url_for('users.register') }}">Registrar-se</a>
		</small>
	</div>


{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
{% for post in posts.items %}
        <article class="media content-section">
		<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
            </div>
	    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
	       {% if posts.page == page_num %}
	       <a class="btn btn-outline-info mb-4 " href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
		{% else %}
	       <a class="btn btn-info mb-4 " href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
	{% endif %}
	{% else %}
	{% endif %}
{% endfor %}
{% endblock content %}

flaskblog/templates/layoutun.html
<!DOCTYPE html>
<html>
<head>
<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
    	<title>AGCO² - {{ title }}</title>
    {% else %}
    	<title>AGCO²</title>
    {% endif %}
</head>
<body class="content-login">
	<header class="site-header">
	      <nav class="navbar navbar-expand-md navbar-dark bg-mento fixed-top">
		<div class="container bg-mento">
		  <img src="static/logo.png" style="width:40px; height:50px;" class="navbar-brand mr4" alt="AGCO²">
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarToggle">
			    <ul style="text-align: center; display: inline-block;">
				    <li style="display: inline-block;" class="nav-item nav-link"><a style="color: white;" href="{{ url_for('noticias.news') }}">Notícias<a/></li>
				    <li style="display: inline-block;"class="nav-item nav-link"><a style="color: white;" href="{{ url_for('cursos.capacit') }}">Capacitação</a></li>
				    <li style="display: inline-block;"class="nav-item nav-link"><a style="color: white;" href="{{ url_for('main.produtores') }}">Produtores</a></li>
			    </ul>
		    <div class="navbar-nav mr-auto">

		    <a style="margin-top: -10px;" class="nav-item nav-link" href="{{ url_for('main.about') }}">Quem Somos</a>
		    <!-- Navbar Right Side -->
		    <div class="navbar-nav">
		    {% if current_user.is_authenticated %}

		    {% else %}
		    <a style="margin-top: -10px;" class="nav-item nav-link" href="{{ url_for('users.login') }}">Entrar</a>
		    <a style="margin-top: -10px;" class="nav-item nav-link" href="{{ url_for('users.register') }}">Registrar-se</a>
		    {% endif %}
		    </div>
		  </div>
		</div>
	      </nav>
	    </header>
	    <main role="main" class="container">
	      <div class="row">
		<div class="col-md-8">
		   {% with messages = get_flashed_messages(with_categories=true) %}
		       {% if messages %}
 		         {% for category, message in messages %}
					<div class="alert alert-{{ category }}">
						{{ message }}	
					</div>
			 {% endfor %}
			{% endif %}
	 	  {% endwith %}

		  {% block content %}{% endblock %}



		</div>
	      </div>
	    </main>
 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Entrar</legend>

				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
						{% if form.email.errors %}
							{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}

				</div>

				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
						{% if form.password.errors %}
							{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-check">
					{{ form.remember(class="form-check-input" )}}
					{{ form.remember.label(class="form-check-label" )}}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info")}}
			<small class="text-muted ml-2">
				<a href="{{ url_for('users.reset_request') }}">Esqueci a senha!</a>
			</small>
			</div>

		</form>
	</div>
	<div>
		<small class="text-muted">
			Precisa de uma conta? <a class="ml-2" href="{{ url_for('users.register') }}">Registrar-se</a>
		</small>
	</div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
	<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
  <div class="media-body">
    <div class="article-metadata">
	    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
      {% if post.author == current_user %}
         <div>
		 <a class="btn-secondary btn-sm m-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Atualizar post</a>
		 <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Deletar</button>
	 </div>
      {% endif %}
    </div>
    <h2 class="article-title">{{ post.title }}</h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
<!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Deletar Postagem?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

flaskblog/templates/produtores.html
{% extends "layout.html" %}
{% block content %}
{% for post in posts.items %}
        <article class="media content-section">
		<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
            </div>
	    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
	       {% if posts.page == page_num %}
	       <a class="btn btn-outline-info mb-4 " href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
		{% else %}
	       <a class="btn btn-info mb-4 " href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
	{% endif %}
	{% else %}
	{% endif %}
{% endfor %}
{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}